### ISSUE TITLE
help me 

### ISSUE THREAD

**Issue by SlookHD** [cybertiger/Bukkit-CreativeItemControl#2]
Could not pass event InventoryCreativeEvent to CreativeItemControl v1.5-antony
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[craftbukkit-1.7.2-R0.3-3020.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.7.2-R0.3-3020.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:486) [craftbukkit-1.7.2-R0.3-3020.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:471) [craftbukkit-1.7.2-R0.3-3020.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
at net.minecraft.server.v1_7_R1.PlayerConnection.a(PlayerConnection.java:1483) [craftbukkit-1.7.2-R0.3-3020.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
at net.minecraft.server.v1_7_R1.PacketPlayInSetCreativeSlot.a(SourceFile:23) [craftbukkit-1.7.2-R0.3-3020.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
at net.minecraft.server.v1_7_R1.PacketPlayInSetCreativeSlot.handle(SourceFile:9) [craftbukkit-1.7.2-R0.3-3020.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
at net.minecraft.server.v1_7_R1.NetworkManager.a(NetworkManager.java:146) [craftbukkit-1.7.2-R0.3-3020.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
at net.minecraft.server.v1_7_R1.ServerConnection.c(SourceFile:134) [craftbukkit-1.7.2-R0.3-3020.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:655) [craftbukkit-1.7.2-R0.3-3020.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:250) [craftbukkit-1.7.2-R0.3-3020.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:545) [craftbukkit-1.7.2-R0.3-3020.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:457) [craftbukkit-1.7.2-R0.3-3020.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [craftbukkit-1.7.2-R0.3-3020.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
Caused by: java.lang.ClassCastException: org.cyberiantiger.minecraft.nbt.ShortTag cannot be cast to org.cyberiantiger.minecraft.nbt.StringTag
at org.cyberiantiger.minecraft.nbt.CompoundTag.getString(CompoundTag.java:132) ~[?:?]
at org.cyberiantiger.minecraft.itemcontrol.Main.checkBlacklist(Main.java:312) ~[?:?]
at org.cyberiantiger.minecraft.itemcontrol.Main.onCreativeEvent(Main.java:216) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45-internal]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45-internal]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45-internal]
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45-internal]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:318) ~[craftbukkit-1.7.2-R0.3-3020.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
... 13 more

**Comment by RoboMWM** [comment]
Not compatible with 1.7.2. Please update from that ancient version.

**Comment by SlookHD** [comment]
but my friend server have 1.7.2 and is compatible?

**Comment by RoboMWM** [comment]
No, it's not compatible.

**Comment by cybertiger** [comment]
As RoboMWM stated, not compatible with 1.7 (latest version is 1.9 only, there's a previous version that's 1.8 compatible).

No plans to add 1.7 support in the near future (My time is limited, specially given the number of people who can find the donate button).
