### ISSUE TITLE
spigot 1.9.4 causing issues with version 1.9

### ISSUE THREAD

**Issue by frizzbee30** [cybertiger/Bukkit-CreativeItemControl#3]
Hi, 1.9.4 has predictably caused an issue, have to love Mojang's development roadmap!

[15:56:22] [Server thread/INFO]: [CreativeItemControl] Enabling CreativeItemControl v1.9-antony
[15:56:22] [Server thread/ERROR]: Error occurred while enabling CreativeItemControl v1.9-antony (Is it up to date?)
java.lang.UnsupportedOperationException: Unsupported CraftBukkit version: 1.9.4-R0.1-SNAPSHOT
    at org.cyberiantiger.minecraft.unsafe.CBShim.unsupportedVersion(CBShim.java:94) ~[?:?]
    at org.cyberiantiger.minecraft.unsafe.CBShim.createShim(CBShim.java:76) ~[?:?]
    at org.cyberiantiger.minecraft.itemcontrol.Main.onEnable(Main.java:178) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[custom.jar:git-Spigot-4af49dc-c5e9a16]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [custom.jar:git-Spigot-4af49dc-c5e9a16]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [custom.jar:git-Spigot-4af49dc-c5e9a16]
    at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:361) [custom.jar:git-Spigot-4af49dc-c5e9a16]
    at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:321) [custom.jar:git-Spigot-4af49dc-c5e9a16]
    at net.minecraft.server.v1_9_R2.MinecraftServer.t(MinecraftServer.java:416) [custom.jar:git-Spigot-4af49dc-c5e9a16]
    at net.minecraft.server.v1_9_R2.MinecraftServer.l(MinecraftServer.java:381) [custom.jar:git-Spigot-4af49dc-c5e9a16]
    at net.minecraft.server.v1_9_R2.MinecraftServer.a(MinecraftServer.java:336) [custom.jar:git-Spigot-4af49dc-c5e9a16]
    at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:268) [custom.jar:git-Spigot-4af49dc-c5e9a16]
    at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [custom.jar:git-Spigot-4af49dc-c5e9a16]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.ClassNotFoundException: org.cyberiantiger.minecraft.unsafe.v1_9_R2.NBTTools
    at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_91]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[custom.jar:git-Spigot-4af49dc-c5e9a16]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[custom.jar:git-Spigot-4af49dc-c5e9a16]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
    at org.cyberiantiger.minecraft.unsafe.CBShim.createShim(CBShim.java:52) ~[?:?]

**Comment by cybertiger** [comment]
Thanks for letting me know I'm aware, and will be updating it shortly.

**Comment by frizzbee30** [comment]
resolved
